### PR TITLE
full test suite for output log expectations (buy, sell, rebuy, rebuild)

### PR DESCRIPTION
**Pull request by atomantic**
Alright, finally cleaned this up and consolidated it.

When running `npm test` or doing a commit (triggering the pre-commit hook), you'll get this (if all goes well):

```
> ./node_modules/eslint/bin/eslint.js . && echo '✅ No Lint' && ./node_modules/jest/bin/jest.js --verbose --coverage && echo '✅ Tests'

✅ No Lint
 PASS  test/request.sign.test.js
  ✓ sign a request (3 ms)

 PASS  test/touch.test.js
  ✓ touch an existing file (3 ms)
  ✓ touch to create a new file (2 ms)

 PASS  test/sleep.test.js
  ✓ sleep 0 (6 ms)
  ✓ sleep 200ms (202 ms)

 PASS  test/math.test.js
  ✓ add number and string: no rounding error (2 ms)
  ✓ subtract number and string: no rounding error
  ✓ multiply number and string: no rounding error (1 ms)
  ✓ divide number and string: no rounding error
  ✓ pow number and string: no rounding error

 PASS  test/index.test.js
  Engine
    ✓ Log Output: 00.boot (4 ms)
    ✓ Log Output: 01.buy (1 ms)
    ✓ Log Output: 02.sell
    ✓ Log Output: 03.rebuy (2 ms)
    ✓ Log Output: 04.rebuild (2 ms)
    ✓ Log Output: 05.rebuy.fill (2 ms)
    ✓ no error outputs

-----------------------------------------|---------|----------|---------|---------|----------------------
File                                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------|---------|----------|---------|---------|----------------------
All files                                |   86.58 |    64.07 |    86.3 |   87.92 |
 coinbase_position_builder_bot           |   84.62 |    54.05 |    87.5 |   87.67 |
  api.keys.js                            |     100 |       50 |     100 |     100 | 12-18
  config.js                              |   84.85 |       50 |     100 |    87.1 | 55-59
  index.js                               |   84.09 |    63.64 |      75 |    87.8 | 33-36,58,68-71
 coinbase_position_builder_bot/coinbase  |      76 |    44.44 |   82.35 |   76.61 |
  accounts.js                            |     100 |       50 |     100 |     100 | 9
  cb.request.js                          |   93.33 |    66.67 |      50 |   93.33 | 41
  delete.order.js                        |   85.71 |       50 |     100 |     100 | 7-13
  get.order.js                           |   59.38 |       30 |     100 |   59.38 | 14,17-20,35-41,44-49
  get.product.js                         |     100 |       50 |     100 |     100 | 11
  get.ticker.js                          |   71.43 |       50 |      50 |   71.43 | 9-13
  http.request.js                        |    69.7 |       50 |   83.33 |    69.7 | 19-20,23,28-35,43-44
  order.js                               |   76.92 |       50 |     100 |   76.92 | 12-13,21
  request.sign.js                        |     100 |      100 |     100 |     100 |
 coinbase_position_builder_bot/lib       |   92.31 |    77.19 |      90 |   92.78 |
  action.js                              |   84.21 |       65 |     100 |   86.49 | 35-36,45,49-52
  calculate.action.js                    |     100 |    94.44 |     100 |     100 | 19
  history.js                             |   80.95 |       60 |   66.67 |   80.95 | 16-19,24-25
  log.js                                 |      80 |       50 |      80 |      80 | 7
  log.output.js                          |     100 |     87.5 |     100 |     100 | 8,32
  log.save.js                            |     100 |      100 |     100 |     100 |
  math.js                                |     100 |      100 |     100 |     100 |
  memory.js                              |     100 |      100 |     100 |     100 |
  number.fix.js                          |     100 |       50 |     100 |     100 | 2
  process.order.js                       |     100 |    83.33 |     100 |     100 | 4
  rebuys.check.js                        |   93.44 |    78.57 |    87.5 |    93.1 | 44-48,84
  rebuys.post.js                         |   90.57 |    66.67 |     100 |    90.2 | 38,54-57,83-88
  sleep.js                               |     100 |      100 |     100 |     100 |
  touch.js                               |   92.31 |    66.67 |     100 |     100 | 9-10
 coinbase_position_builder_bot/test      |     100 |      100 |     100 |     100 |
  test.config.js                         |     100 |      100 |     100 |     100 |
 coinbase_position_builder_bot/test/lib  |   66.67 |       25 |      60 |   76.92 |
  get.id.js                              |    87.5 |       50 |     100 |     100 | 58
  get.log.js                             |     100 |      100 |     100 |     100 |
  log.js                                 |      50 |    16.67 |   33.33 |      60 | 32-34,37-39
  test.memory.js                         |     100 |      100 |     100 |     100 |
 coinbase_position_builder_bot/test/nock |   96.15 |       95 |     100 |   96.08 |
  delete.order.js                        |     100 |      100 |     100 |     100 |
  get.accounts.js                        |     100 |      100 |     100 |     100 |
  get.order.js                           |   84.62 |       75 |     100 |   84.62 | 13-14
  get.product.js                         |     100 |      100 |     100 |     100 |
  get.ticker.js                          |     100 |      100 |     100 |     100 |
  post.orders.js                         |     100 |      100 |     100 |     100 |
-----------------------------------------|---------|----------|---------|---------|----------------------
Test Suites: 5 passed, 5 total
Tests:       17 passed, 17 total
Snapshots:   0 total
Time:        4.275 s
Ran all test suites.
✅ Tests
```

and then you can view the coverage report with open `coverage/lcov-report/index.html`.

Maintaining the tests is pretty simple. You just edit the ./test/data/output* files to match what you get when you run a manual: `npm run test:debug` (which will output the log data for you to copy/paste if anything changed from the current expectation).

To add new expectation sets, you can configure the first section of `./test/index.test.js`, which is the main test runner.

### CODE REVIEW

**Comment by jasonedison** [comment]
Bravo! Are all the missed lines things that are failsafes? I'll run it now and check it out. Is 100% coverage something worth trying to attain?

**Comment by jasonedison** [comment]
Looks like some files are missing:

```
 Engine › Log Output: 00.boot

    ENOENT: no such file or directory

      3 | module.exports = name =>
      4 |   fs
    > 5 |     .readFileSync(`${__dirname}/../data/output.${name}.log`)
        |      ^
      6 |     .toString()
      7 |     .split('\n');
      8 |

      at getLog (test/lib/get.log.js:5:6)
      at Object.<anonymous> (test/index.test.js:87:27)
```

**Comment by atomantic** [comment]
whoops. .gitignore :)

**Comment by jasonedison** [comment]
Sweet! Got it. I see the coverage report is missing on things like error logging. Merging now and I'll play around with it.

**Pull request merged**
